### ISSUE TITLE
@import "Pattern"; doesn't work

### ISSUE THREAD

**Issue by Dangoo** [sinnerschrader/patternplate-transform-postcss#1] opened 2016-02-22 15:08 UTC
### Input
```css
/* index.css */
:root {
  --background-color: #f00;
}
```

```css
/* demo.css */
@import "Pattern";

.bar {
  background-color: var(--background-color);
}
```

### Actual
A `demo.css` file with an `@import "Pattern";` statement fails with the error message
```
Error in "globals/colors" during transform "postcss" of "<root>/patterns/globals/colors/demo.css": Cannot find module 'Pattern'`
```

### Expected
A `demo.css` file with an `@import "Pattern";` resolves to `index.css`

### Notes
When removing `@import "Pattern";`
The error message says:
```
Error in "globals/colors" during transform "postcss" of "<root>/patterns/globals/colors/demo.css": Cannot read property 'indexOf' of undefined
```

**Comment by marionebl** [comment] 2016-02-22 18:30
The bug causing 

```css
@import "Pattern";
```

to fail is fixed with [v0.1.2](https://github.com/sinnerschrader/patternplate-transform-postcss/releases/tag/v0.1.2).

As for the layered error `Cannot read property 'indexOf' of undefined`: I played around a bit with the test scenario you provided of the record and found it to be caused by `var(--foo)` statements where `--foo` was not defined – I suggest you file an issue at [postcss-css-variables](https://github.com/MadLittleMods/postcss-css-variables) prompting for better error messages, or better yet, submit a PR there.

**Closed by marionebl** 2016-02-22 18:30 UTC
Labels: bug
